name: Java CI/CD Pipeline

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: SSH 설정
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: SSH 연결 유지 설정
        run: |
          mkdir -p ~/.ssh
          echo "Host *" > ~/.ssh/config
          echo "  ServerAliveInterval 60" >> ~/.ssh/config
          echo "  ServerAliveCountMax 10" >> ~/.ssh/config

      - name: 원격 EC2 서버에서 Git Pull 및 Docker 실행
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST }} << 'EOF'
            # 디렉토리 존재 여부 확인
            REPO_DIR="/home/ubuntu/backend/SIST-Docker-back"
            
            if [ -d "$REPO_DIR" ]; then
              # 디렉토리가 존재하면 모든 로컬 변경사항 폐기 후 업데이트
              echo "프로젝트 디렉토리가 존재합니다. 강제 업데이트를 진행합니다."
              cd "$REPO_DIR"
              git reset --hard
              git fetch
              git pull origin main
            else
              # 디렉토리가 존재하지 않으면 클론
              echo "프로젝트 디렉토리가 존재하지 않습니다. 클론을 진행합니다."
              mkdir -p "$(dirname "$REPO_DIR")"
              git clone https://github.com/ted19horse/SIST-Docker-back.git "$REPO_DIR"
              cd "$REPO_DIR"
            fi
            
            # 필요한 디렉토리 생성 (db 디렉토리가 없을 경우에만)
            if [ ! -d "$REPO_DIR/db" ]; then
              echo "db 디렉토리를 생성합니다."
              mkdir -p "$REPO_DIR/db"
            else
              echo "기존 db 디렉토리가 존재합니다. 볼륨 데이터를 보존합니다."
            fi
            
            # Docker 관련 권한 설정
            sudo chmod -R 777 "$REPO_DIR"
            sudo chmod 666 /var/run/docker.sock
            
            # 네트워크 존재 여부 확인 및 생성
            if ! docker network ls | grep -q sist_net; then
              echo "sist_net 네트워크를 생성합니다."
              docker network create sist_net
            fi
            
            # Docker Compose 실행
            cd "$REPO_DIR"
            docker-compose down
            docker-compose up -d --build
          EOF
